# Add 'repo' label to any root file changes
repo:
  - ./*

documentation:
  - .github/ISSUE_TEMPLATE/*
  - .github/PULL_REQUEST_TEMPLATE.md
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md

tests:
  - Tests/**/*