version: 2.0

references:

  workspace_root: &workspace_root
                    ~/workspace

  container_config: &container_config
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: *workspace_root

    environment:
      TERM: dumb
      JVM_OPTS: -Xmx4096m

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  general_cache_key: &general_cache_key
    key: app-{{ checksum "build.gradle.kts" }}-{{ checksum "library/build.gradle.kts" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:

  build:
    <<: *container_config
    steps:
      - checkout

      - restore_cache:
          <<: *general_cache_key
      - run:
          name: Setup environment
          command: scripts/setup.sh
      - save_cache:
          <<: *general_cache_key
          paths:
            - "~/.gradle"
            - "~/.m2"

      - run:
          name: Build
          command: scripts/build.sh

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  check:
    <<: *container_config
    steps:
      - *attach_workspace

      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Run Checks
          command: scripts/check.sh

      - store_artifacts:
          path: library/build/reports/
          destination: reports/library/

      - store_test_results:
          path: library/build/test-results

workflows:
  version: 2

  check_deploy:
    jobs:
      - build
      - check:
          requires:
            - build
