build:
    maxIssues: 1

comments:
    DeprecatedBlockTag:
        active: true
    EndOfSentenceFormat:
        active: true
    KDocReferencesNonPublicProperty:
        active: true
    OutdatedDocumentation:
        active: true
    UndocumentedPublicClass:
        active: true
    UndocumentedPublicFunction:
        active: true
    UndocumentedPublicProperty:
        active: true

complexity:
    CognitiveComplexMethod:
        active: true
    ComplexInterface:
        active: true
    CyclomaticComplexMethod:
        ignoreSingleWhenExpression: true
    LargeClass:
        active: false
    LongMethod:
        active: false
    LongParameterList:
        active: false
    TooManyFunctions:
        active: false

coroutines:
    GlobalCoroutineUsage:
        active: true
    SuspendFunSwallowedCancellation:
        active: true
    SuspendFunWithCoroutineScopeReceiver:
        active: true

empty-blocks:
    EmptyFunctionBlock:
        ignoreOverridden: true

exceptions:
    NotImplementedDeclaration:
        active: true
    ObjectExtendsThrowable:
        active: true
    ThrowingExceptionInMain:
        active: true

naming:
    BooleanPropertyNaming:
        active: true

performance:
    CouldBeSequence:
        active: true
    UnnecessaryPartOfBinaryExpression:
        active: true

potential-bugs:
    CastNullableToNonNullableType:
        active: true
    CastToNullableType:
        active: true
    Deprecation:
        active: true
    DontDowncastCollectionTypes:
        active: true
    ElseCaseInsteadOfExhaustiveWhen:
        active: true
    ExitOutsideMain:
        active: true
    ImplicitUnitReturnType:
        active: true
    LateinitUsage:
        active: true
    NullCheckOnMutableProperty:
        active: true
    NullableToStringCall:
        active: true
    PropertyUsedBeforeDeclaration:
        active: true
    UnconditionalJumpStatementInLoop:
        active: true
    UnnecessaryNotNullCheck:
        active: true

style:
    AlsoCouldBeApply:
        active: true
    BracesOnIfStatements:
        active: true
        singleLine: 'always'
        multiLine: 'always'
    BracesOnWhenStatements:
        active: true
        singleLine: 'necessary'
        multiLine: 'always'
    CanBeNonNullable:
        active: true
    DataClassShouldBeImmutable:
        active: true
    DoubleNegativeLambda:
        active: true
    EqualsOnSignatureLine:
        active: true
    ExplicitCollectionElementAccessMethod:
        active: true
    ExpressionBodySyntax:
        active: true
    ForbiddenAnnotation:
        active: true
    ForbiddenMethodCall:
        active: true
    MagicNumber:
        ignoreAnnotation: true
    MandatoryBracesLoops:
        active: true
    MultilineLambdaItParameter:
        active: true
    MultilineRawStringIndentation:
        active: true
    NoTabs:
        active: true
    OptionalUnit:
        active: true
    OptionalWhenBraces:
        active: true
    PreferToOverPairSyntax:
        active: true
    RedundantExplicitType:
        active: true
    RedundantVisibilityModifierRule:
        active: true
    ReturnCount:
        active: false
    SpacingBetweenPackageAndImports:
        active: true
    StringShouldBeRawString:
        active: true
    TrailingWhitespace:
        active: true
    ThrowsCount:
        active: false
    UnderscoresInNumericLiterals:
        active: true
    UnnecessaryBackticks:
        active: true
    UnnecessaryInnerClass:
        active: true
    UnnecessaryLet:
        active: true
    UnnecessaryParentheses:
        active: true
    UntilInsteadOfRangeTo:
        active: true
    UnusedImports:
        active: true
    UseEmptyCounterpart:
        active: true
    UseIfEmptyOrIfBlank:
        active: true
    UseLet:
        active: true
    UseSumOfInsteadOfFlatMapSize:
        active: true
